"""Adiciona os tipos do datetime para Date

Revision ID: 2bb0613564a9
Revises: 199d671a1d5a
Create Date: 2024-05-08 23:10:34.132905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb0613564a9'
down_revision: Union[str, None] = '199d671a1d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
